#!/bin/bash

sudo launchctl stop com.bunchenterprise.blend
sudo launchctl unload /Library/LaunchDaemons/com.bunchenterprise.blend.plist
sudo rm /Library/LaunchDaemons/com.bunchenterprise.blend.plist
sudo rm -rf /usr/local/blend
