// flow-typed signature: 5aa9879bf15ab5929498c034efa71a59
// flow-typed version: <<STUB>>/bl_v^3.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bl/bl' {
  declare module.exports: any;
}

declare module 'bl/test/indexOf' {
  declare module.exports: any;
}

declare module 'bl/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bl/bl.js' {
  declare module.exports: $Exports<'bl/bl'>;
}
declare module 'bl/test/indexOf.js' {
  declare module.exports: $Exports<'bl/test/indexOf'>;
}
declare module 'bl/test/test.js' {
  declare module.exports: $Exports<'bl/test/test'>;
}
