// flow-typed signature: ad588eb6a8439bcdc834bea85685c4a8
// flow-typed version: <<STUB>>/buffer-slice_v^0.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-slice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-slice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buffer-slice/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buffer-slice/index' {
  declare module.exports: $Exports<'buffer-slice'>;
}
declare module 'buffer-slice/index.js' {
  declare module.exports: $Exports<'buffer-slice'>;
}
declare module 'buffer-slice/test.js' {
  declare module.exports: $Exports<'buffer-slice/test'>;
}
