// flow-typed signature: d177c1c65aea5b10e7f08f7f63168be7
// flow-typed version: <<STUB>>/express-graceful-exit_v^0.4.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-graceful-exit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-graceful-exit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-graceful-exit/lib/graceful-exit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-graceful-exit/index' {
  declare module.exports: $Exports<'express-graceful-exit'>;
}
declare module 'express-graceful-exit/index.js' {
  declare module.exports: $Exports<'express-graceful-exit'>;
}
declare module 'express-graceful-exit/lib/graceful-exit.js' {
  declare module.exports: $Exports<'express-graceful-exit/lib/graceful-exit'>;
}
