// flow-typed signature: 9530d42cc74854cb2762d345bb70bd2d
// flow-typed version: <<STUB>>/flatted_v^2.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flatted'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flatted' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flatted/cjs/index' {
  declare module.exports: any;
}

declare module 'flatted/esm/index' {
  declare module.exports: any;
}

declare module 'flatted/min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flatted/cjs/index.js' {
  declare module.exports: $Exports<'flatted/cjs/index'>;
}
declare module 'flatted/esm/index.js' {
  declare module.exports: $Exports<'flatted/esm/index'>;
}
declare module 'flatted/index' {
  declare module.exports: $Exports<'flatted'>;
}
declare module 'flatted/index.js' {
  declare module.exports: $Exports<'flatted'>;
}
declare module 'flatted/min.js' {
  declare module.exports: $Exports<'flatted/min'>;
}
