// flow-typed signature: cb72d9b32847ac8f677f08b45a923f3e
// flow-typed version: <<STUB>>/murmurhash3js_v^3.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'murmurhash3js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'murmurhash3js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'murmurhash3js/examples/node' {
  declare module.exports: any;
}

declare module 'murmurhash3js/Gruntfile' {
  declare module.exports: any;
}

declare module 'murmurhash3js/lib/murmurHash3js' {
  declare module.exports: any;
}

declare module 'murmurhash3js/murmurhash3js.min' {
  declare module.exports: any;
}

declare module 'murmurhash3js/test/test-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'murmurhash3js/examples/node.js' {
  declare module.exports: $Exports<'murmurhash3js/examples/node'>;
}
declare module 'murmurhash3js/Gruntfile.js' {
  declare module.exports: $Exports<'murmurhash3js/Gruntfile'>;
}
declare module 'murmurhash3js/index' {
  declare module.exports: $Exports<'murmurhash3js'>;
}
declare module 'murmurhash3js/index.js' {
  declare module.exports: $Exports<'murmurhash3js'>;
}
declare module 'murmurhash3js/lib/murmurHash3js.js' {
  declare module.exports: $Exports<'murmurhash3js/lib/murmurHash3js'>;
}
declare module 'murmurhash3js/murmurhash3js.min.js' {
  declare module.exports: $Exports<'murmurhash3js/murmurhash3js.min'>;
}
declare module 'murmurhash3js/test/test-server.js' {
  declare module.exports: $Exports<'murmurhash3js/test/test-server'>;
}
