// flow-typed signature: fb8d5228a3ed2c973a5186118b09aca4
// flow-typed version: <<STUB>>/mux.js_v^5.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mux.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mux.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mux.js/dist/mux-flv' {
  declare module.exports: any;
}

declare module 'mux.js/dist/mux-flv.min' {
  declare module.exports: any;
}

declare module 'mux.js/dist/mux-mp4' {
  declare module.exports: any;
}

declare module 'mux.js/dist/mux-mp4.min' {
  declare module.exports: any;
}

declare module 'mux.js/dist/mux' {
  declare module.exports: any;
}

declare module 'mux.js/dist/mux.min' {
  declare module.exports: any;
}

declare module 'mux.js/lib/aac/index' {
  declare module.exports: any;
}

declare module 'mux.js/lib/aac/utils' {
  declare module.exports: any;
}

declare module 'mux.js/lib/codecs/adts' {
  declare module.exports: any;
}

declare module 'mux.js/lib/codecs/h264' {
  declare module.exports: any;
}

declare module 'mux.js/lib/codecs/index' {
  declare module.exports: any;
}

declare module 'mux.js/lib/data/silence' {
  declare module.exports: any;
}

declare module 'mux.js/lib/flv/coalesce-stream' {
  declare module.exports: any;
}

declare module 'mux.js/lib/flv/flv-header' {
  declare module.exports: any;
}

declare module 'mux.js/lib/flv/flv-tag' {
  declare module.exports: any;
}

declare module 'mux.js/lib/flv/index' {
  declare module.exports: any;
}

declare module 'mux.js/lib/flv/tag-list' {
  declare module.exports: any;
}

declare module 'mux.js/lib/flv/transmuxer' {
  declare module.exports: any;
}

declare module 'mux.js/lib/index' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/caption-stream' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/index' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/m2ts' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/metadata-stream' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/probe' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/stream-types' {
  declare module.exports: any;
}

declare module 'mux.js/lib/m2ts/timestamp-rollover-stream' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/audio-frame-utils' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/caption-parser' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/frame-utils' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/index' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/mp4-generator' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/probe' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/track-decode-info' {
  declare module.exports: any;
}

declare module 'mux.js/lib/mp4/transmuxer' {
  declare module.exports: any;
}

declare module 'mux.js/lib/tools/caption-packet-parser' {
  declare module.exports: any;
}

declare module 'mux.js/lib/tools/flv-inspector' {
  declare module.exports: any;
}

declare module 'mux.js/lib/tools/mp4-inspector' {
  declare module.exports: any;
}

declare module 'mux.js/lib/tools/ts-inspector' {
  declare module.exports: any;
}

declare module 'mux.js/lib/utils/bin' {
  declare module.exports: any;
}

declare module 'mux.js/lib/utils/clock' {
  declare module.exports: any;
}

declare module 'mux.js/lib/utils/exp-golomb' {
  declare module.exports: any;
}

declare module 'mux.js/lib/utils/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mux.js/dist/mux-flv.js' {
  declare module.exports: $Exports<'mux.js/dist/mux-flv'>;
}
declare module 'mux.js/dist/mux-flv.min.js' {
  declare module.exports: $Exports<'mux.js/dist/mux-flv.min'>;
}
declare module 'mux.js/dist/mux-mp4.js' {
  declare module.exports: $Exports<'mux.js/dist/mux-mp4'>;
}
declare module 'mux.js/dist/mux-mp4.min.js' {
  declare module.exports: $Exports<'mux.js/dist/mux-mp4.min'>;
}
declare module 'mux.js/dist/mux.js' {
  declare module.exports: $Exports<'mux.js/dist/mux'>;
}
declare module 'mux.js/dist/mux.min.js' {
  declare module.exports: $Exports<'mux.js/dist/mux.min'>;
}
declare module 'mux.js/lib/aac/index.js' {
  declare module.exports: $Exports<'mux.js/lib/aac/index'>;
}
declare module 'mux.js/lib/aac/utils.js' {
  declare module.exports: $Exports<'mux.js/lib/aac/utils'>;
}
declare module 'mux.js/lib/codecs/adts.js' {
  declare module.exports: $Exports<'mux.js/lib/codecs/adts'>;
}
declare module 'mux.js/lib/codecs/h264.js' {
  declare module.exports: $Exports<'mux.js/lib/codecs/h264'>;
}
declare module 'mux.js/lib/codecs/index.js' {
  declare module.exports: $Exports<'mux.js/lib/codecs/index'>;
}
declare module 'mux.js/lib/data/silence.js' {
  declare module.exports: $Exports<'mux.js/lib/data/silence'>;
}
declare module 'mux.js/lib/flv/coalesce-stream.js' {
  declare module.exports: $Exports<'mux.js/lib/flv/coalesce-stream'>;
}
declare module 'mux.js/lib/flv/flv-header.js' {
  declare module.exports: $Exports<'mux.js/lib/flv/flv-header'>;
}
declare module 'mux.js/lib/flv/flv-tag.js' {
  declare module.exports: $Exports<'mux.js/lib/flv/flv-tag'>;
}
declare module 'mux.js/lib/flv/index.js' {
  declare module.exports: $Exports<'mux.js/lib/flv/index'>;
}
declare module 'mux.js/lib/flv/tag-list.js' {
  declare module.exports: $Exports<'mux.js/lib/flv/tag-list'>;
}
declare module 'mux.js/lib/flv/transmuxer.js' {
  declare module.exports: $Exports<'mux.js/lib/flv/transmuxer'>;
}
declare module 'mux.js/lib/index.js' {
  declare module.exports: $Exports<'mux.js/lib/index'>;
}
declare module 'mux.js/lib/m2ts/caption-stream.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/caption-stream'>;
}
declare module 'mux.js/lib/m2ts/index.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/index'>;
}
declare module 'mux.js/lib/m2ts/m2ts.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/m2ts'>;
}
declare module 'mux.js/lib/m2ts/metadata-stream.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/metadata-stream'>;
}
declare module 'mux.js/lib/m2ts/probe.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/probe'>;
}
declare module 'mux.js/lib/m2ts/stream-types.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/stream-types'>;
}
declare module 'mux.js/lib/m2ts/timestamp-rollover-stream.js' {
  declare module.exports: $Exports<'mux.js/lib/m2ts/timestamp-rollover-stream'>;
}
declare module 'mux.js/lib/mp4/audio-frame-utils.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/audio-frame-utils'>;
}
declare module 'mux.js/lib/mp4/caption-parser.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/caption-parser'>;
}
declare module 'mux.js/lib/mp4/frame-utils.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/frame-utils'>;
}
declare module 'mux.js/lib/mp4/index.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/index'>;
}
declare module 'mux.js/lib/mp4/mp4-generator.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/mp4-generator'>;
}
declare module 'mux.js/lib/mp4/probe.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/probe'>;
}
declare module 'mux.js/lib/mp4/track-decode-info.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/track-decode-info'>;
}
declare module 'mux.js/lib/mp4/transmuxer.js' {
  declare module.exports: $Exports<'mux.js/lib/mp4/transmuxer'>;
}
declare module 'mux.js/lib/tools/caption-packet-parser.js' {
  declare module.exports: $Exports<'mux.js/lib/tools/caption-packet-parser'>;
}
declare module 'mux.js/lib/tools/flv-inspector.js' {
  declare module.exports: $Exports<'mux.js/lib/tools/flv-inspector'>;
}
declare module 'mux.js/lib/tools/mp4-inspector.js' {
  declare module.exports: $Exports<'mux.js/lib/tools/mp4-inspector'>;
}
declare module 'mux.js/lib/tools/ts-inspector.js' {
  declare module.exports: $Exports<'mux.js/lib/tools/ts-inspector'>;
}
declare module 'mux.js/lib/utils/bin.js' {
  declare module.exports: $Exports<'mux.js/lib/utils/bin'>;
}
declare module 'mux.js/lib/utils/clock.js' {
  declare module.exports: $Exports<'mux.js/lib/utils/clock'>;
}
declare module 'mux.js/lib/utils/exp-golomb.js' {
  declare module.exports: $Exports<'mux.js/lib/utils/exp-golomb'>;
}
declare module 'mux.js/lib/utils/stream.js' {
  declare module.exports: $Exports<'mux.js/lib/utils/stream'>;
}
