// flow-typed signature: 7fdf475bf99c47098272da031ee6e39f
// flow-typed version: <<STUB>>/pem_v^1.14.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pem/lib/convert' {
  declare module.exports: any;
}

declare module 'pem/lib/helper' {
  declare module.exports: any;
}

declare module 'pem/lib/openssl' {
  declare module.exports: any;
}

declare module 'pem/lib/pem' {
  declare module.exports: any;
}

declare module 'pem/test/convert.spec' {
  declare module.exports: any;
}

declare module 'pem/test/helper.spec' {
  declare module.exports: any;
}

declare module 'pem/test/openssl.spec' {
  declare module.exports: any;
}

declare module 'pem/test/pem.helper' {
  declare module.exports: any;
}

declare module 'pem/test/pem.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pem/lib/convert.js' {
  declare module.exports: $Exports<'pem/lib/convert'>;
}
declare module 'pem/lib/helper.js' {
  declare module.exports: $Exports<'pem/lib/helper'>;
}
declare module 'pem/lib/openssl.js' {
  declare module.exports: $Exports<'pem/lib/openssl'>;
}
declare module 'pem/lib/pem.js' {
  declare module.exports: $Exports<'pem/lib/pem'>;
}
declare module 'pem/test/convert.spec.js' {
  declare module.exports: $Exports<'pem/test/convert.spec'>;
}
declare module 'pem/test/helper.spec.js' {
  declare module.exports: $Exports<'pem/test/helper.spec'>;
}
declare module 'pem/test/openssl.spec.js' {
  declare module.exports: $Exports<'pem/test/openssl.spec'>;
}
declare module 'pem/test/pem.helper.js' {
  declare module.exports: $Exports<'pem/test/pem.helper'>;
}
declare module 'pem/test/pem.spec.js' {
  declare module.exports: $Exports<'pem/test/pem.spec'>;
}
