// flow-typed signature: 16211db849f6c5e62da787149b410273
// flow-typed version: <<STUB>>/simple-peer_v^9.1.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-peer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-peer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-peer/simplepeer.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-peer/index' {
  declare module.exports: $Exports<'simple-peer'>;
}
declare module 'simple-peer/index.js' {
  declare module.exports: $Exports<'simple-peer'>;
}
declare module 'simple-peer/simplepeer.min.js' {
  declare module.exports: $Exports<'simple-peer/simplepeer.min'>;
}
