// flow-typed signature: 8945aab529b3e12c758d139b4ba84bfe
// flow-typed version: <<STUB>>/uWebSockets.js_vuNetworking/uWebSockets.js#v15.8.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uWebSockets.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uWebSockets.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uWebSockets.js/uws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uWebSockets.js/uws.js' {
  declare module.exports: $Exports<'uWebSockets.js/uws'>;
}
