// flow-typed signature: a95a3b2e101e96ed30a02a671b7e19ee
// flow-typed version: <<STUB>>/can-autoplay_v^3.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'can-autoplay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'can-autoplay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'can-autoplay/build/can-autoplay.cjs' {
  declare module.exports: any;
}

declare module 'can-autoplay/build/can-autoplay.es' {
  declare module.exports: any;
}

declare module 'can-autoplay/build/can-autoplay' {
  declare module.exports: any;
}

declare module 'can-autoplay/build/can-autoplay.min' {
  declare module.exports: any;
}

declare module 'can-autoplay/lib/index' {
  declare module.exports: any;
}

declare module 'can-autoplay/lib/media' {
  declare module.exports: any;
}

declare module 'can-autoplay/rollup.config' {
  declare module.exports: any;
}

declare module 'can-autoplay/test/audio.spec' {
  declare module.exports: any;
}

declare module 'can-autoplay/test/common' {
  declare module.exports: any;
}

declare module 'can-autoplay/test/setup' {
  declare module.exports: any;
}

declare module 'can-autoplay/test/video.spec' {
  declare module.exports: any;
}

declare module 'can-autoplay/tools/blob-generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'can-autoplay/build/can-autoplay.cjs.js' {
  declare module.exports: $Exports<'can-autoplay/build/can-autoplay.cjs'>;
}
declare module 'can-autoplay/build/can-autoplay.es.js' {
  declare module.exports: $Exports<'can-autoplay/build/can-autoplay.es'>;
}
declare module 'can-autoplay/build/can-autoplay.js' {
  declare module.exports: $Exports<'can-autoplay/build/can-autoplay'>;
}
declare module 'can-autoplay/build/can-autoplay.min.js' {
  declare module.exports: $Exports<'can-autoplay/build/can-autoplay.min'>;
}
declare module 'can-autoplay/lib/index.js' {
  declare module.exports: $Exports<'can-autoplay/lib/index'>;
}
declare module 'can-autoplay/lib/media.js' {
  declare module.exports: $Exports<'can-autoplay/lib/media'>;
}
declare module 'can-autoplay/rollup.config.js' {
  declare module.exports: $Exports<'can-autoplay/rollup.config'>;
}
declare module 'can-autoplay/test/audio.spec.js' {
  declare module.exports: $Exports<'can-autoplay/test/audio.spec'>;
}
declare module 'can-autoplay/test/common.js' {
  declare module.exports: $Exports<'can-autoplay/test/common'>;
}
declare module 'can-autoplay/test/setup.js' {
  declare module.exports: $Exports<'can-autoplay/test/setup'>;
}
declare module 'can-autoplay/test/video.spec.js' {
  declare module.exports: $Exports<'can-autoplay/test/video.spec'>;
}
declare module 'can-autoplay/tools/blob-generator.js' {
  declare module.exports: $Exports<'can-autoplay/tools/blob-generator'>;
}
