// flow-typed signature: 8e3b639079bb560f766a6740b92e112a
// flow-typed version: <<STUB>>/drag-drop_v^3.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'drag-drop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'drag-drop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'drag-drop/buffer' {
  declare module.exports: any;
}

declare module 'drag-drop/dragdrop.min' {
  declare module.exports: any;
}

declare module 'drag-drop/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'drag-drop/buffer.js' {
  declare module.exports: $Exports<'drag-drop/buffer'>;
}
declare module 'drag-drop/dragdrop.min.js' {
  declare module.exports: $Exports<'drag-drop/dragdrop.min'>;
}
declare module 'drag-drop/index' {
  declare module.exports: $Exports<'drag-drop'>;
}
declare module 'drag-drop/index.js' {
  declare module.exports: $Exports<'drag-drop'>;
}
declare module 'drag-drop/test/basic.js' {
  declare module.exports: $Exports<'drag-drop/test/basic'>;
}
