// flow-typed signature: 0a958e5ae13ff070eac6f74671bb2eb1
// flow-typed version: <<STUB>>/echarts-gl_v^1.1.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'echarts-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'echarts-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'echarts-gl/dist/echarts-gl' {
  declare module.exports: any;
}

declare module 'echarts-gl/dist/echarts-gl.min' {
  declare module.exports: any;
}

declare module 'echarts-gl/rollup.config' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/bar3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/bar3D/bar3DLayout' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/bar3D/Bar3DSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/bar3D/Bar3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/bar3D/cartesian3DLayout' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/bar3D/evaluateBarSparseness' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/createList' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/formatTooltip' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/GLViewHelper' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/opacityVisual' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/PointsBuilder' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/PointsMesh' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/common/sdfSprite.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/flowGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/flowGL/FlowGLSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/flowGL/FlowGLView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/flowGL/Line2D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/flowGL/vectorFieldParticle.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/flowGL/VectorFieldParticleSurface' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/createGraphFromNodeEdge' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/forceAtlas2.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/ForceAtlas2' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/ForceAtlas2GPU' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/forceAtlas2Worker' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/GraphGLSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/graphGL/GraphGLView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/line3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/line3D/Line3DSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/line3D/Line3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/lines3DLayout' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/Lines3DSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/Lines3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/shader/trail.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/shader/trail2.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/TrailGeometry' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/TrailMesh' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/lines3D/TrailMesh2' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/linesGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/linesGL/LinesGLSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/linesGL/LinesGLView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/map3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/map3D/Map3DSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/map3D/Map3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/polygons3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/polygons3D/Polygons3DSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/polygons3D/Polygons3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/scatter3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/scatter3D/Scatter3DSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/scatter3D/Scatter3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/scatterGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/scatterGL/ScatterGLSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/scatterGL/ScatterGLView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/surface' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/surface/surfaceLayout' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/surface/SurfaceSeries' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/chart/surface/SurfaceView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/componentLightMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/componentPostEffectMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/componentShadingMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/componentViewControlMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/Geo3DBuilder' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/LabelsBuilder' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/common/SceneHelper' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/geo3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/geo3D/Geo3DModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/geo3D/Geo3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/globe' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/globe/GlobeModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/globe/GlobeView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/axis3DDefault' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/Axis3DModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/createAxis3DModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/Grid3DAxis' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/Grid3DFace' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/Grid3DModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/grid3D/Grid3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/mapbox3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/mapbox3D/Mapbox3DLayer' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/mapbox3D/Mapbox3DModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/mapbox3D/Mapbox3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/maptalks3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/maptalks3D/Maptalks3DLayer' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/maptalks3D/Maptalks3DModel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/component/maptalks3D/Maptalks3DView' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/geo3D/Geo3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/geo3D/geo3DModelMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/geo3DCreator' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/globe/Globe' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/globeCreator' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/grid3D/Axis3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/grid3D/Cartesian3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/grid3DCreator' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/mapbox3D/Mapbox3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/mapbox3DCreator' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/mapServiceCommon/createMapService3DCreator' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/mapServiceCommon/MapService3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/maptalks3D/Maptalks3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/coord/maptalks3DCreator' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/core/LayerGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/core/ViewGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/echarts-gl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/composite' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/compositeMobile' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/DOF.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/edge.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/EdgePass' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/EffectCompositor' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/halton' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/NormalPass' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/poissonKernel' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/SSAO.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/SSAOPass' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/SSR.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/SSRPass' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/effect/TemporalSuperSampling' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/preprocessor/backwardCompat' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/animatableMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/earcut' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/EChartsSurface' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/format' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/Bars3DGeometry' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/dynamicConvertMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/Lines2D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/Lines3D' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/Quads' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/Sprites' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/trianglesSortMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/geometry/verticesSortMixin' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/graphicGL' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/mesh/LabelsMesh' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/OrbitControl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/ProgressiveQuickSort' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/retrieve' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/Roam2DControl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/color.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/common.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/displayShadow.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/hatching.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/labels.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/lambert.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/lines2D.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/lines3D.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/motionBlur.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/normal.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/realistic.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/shader/shadow.glsl' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/sprite' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/sunCalc' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/Triangulation' {
  declare module.exports: any;
}

declare module 'echarts-gl/src/util/ZRTextureAtlasSurface' {
  declare module.exports: any;
}

declare module 'echarts-gl/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'echarts-gl/dist/echarts-gl.js' {
  declare module.exports: $Exports<'echarts-gl/dist/echarts-gl'>;
}
declare module 'echarts-gl/dist/echarts-gl.min.js' {
  declare module.exports: $Exports<'echarts-gl/dist/echarts-gl.min'>;
}
declare module 'echarts-gl/index' {
  declare module.exports: $Exports<'echarts-gl'>;
}
declare module 'echarts-gl/index.js' {
  declare module.exports: $Exports<'echarts-gl'>;
}
declare module 'echarts-gl/rollup.config.js' {
  declare module.exports: $Exports<'echarts-gl/rollup.config'>;
}
declare module 'echarts-gl/src/chart/bar3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/bar3D'>;
}
declare module 'echarts-gl/src/chart/bar3D/bar3DLayout.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/bar3D/bar3DLayout'>;
}
declare module 'echarts-gl/src/chart/bar3D/Bar3DSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/bar3D/Bar3DSeries'>;
}
declare module 'echarts-gl/src/chart/bar3D/Bar3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/bar3D/Bar3DView'>;
}
declare module 'echarts-gl/src/chart/bar3D/cartesian3DLayout.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/bar3D/cartesian3DLayout'>;
}
declare module 'echarts-gl/src/chart/bar3D/evaluateBarSparseness.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/bar3D/evaluateBarSparseness'>;
}
declare module 'echarts-gl/src/chart/common/createList.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/createList'>;
}
declare module 'echarts-gl/src/chart/common/formatTooltip.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/formatTooltip'>;
}
declare module 'echarts-gl/src/chart/common/GLViewHelper.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/GLViewHelper'>;
}
declare module 'echarts-gl/src/chart/common/opacityVisual.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/opacityVisual'>;
}
declare module 'echarts-gl/src/chart/common/PointsBuilder.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/PointsBuilder'>;
}
declare module 'echarts-gl/src/chart/common/PointsMesh.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/PointsMesh'>;
}
declare module 'echarts-gl/src/chart/common/sdfSprite.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/common/sdfSprite.glsl'>;
}
declare module 'echarts-gl/src/chart/flowGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/flowGL'>;
}
declare module 'echarts-gl/src/chart/flowGL/FlowGLSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/flowGL/FlowGLSeries'>;
}
declare module 'echarts-gl/src/chart/flowGL/FlowGLView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/flowGL/FlowGLView'>;
}
declare module 'echarts-gl/src/chart/flowGL/Line2D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/flowGL/Line2D'>;
}
declare module 'echarts-gl/src/chart/flowGL/vectorFieldParticle.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/flowGL/vectorFieldParticle.glsl'>;
}
declare module 'echarts-gl/src/chart/flowGL/VectorFieldParticleSurface.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/flowGL/VectorFieldParticleSurface'>;
}
declare module 'echarts-gl/src/chart/graphGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL'>;
}
declare module 'echarts-gl/src/chart/graphGL/createGraphFromNodeEdge.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/createGraphFromNodeEdge'>;
}
declare module 'echarts-gl/src/chart/graphGL/forceAtlas2.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/forceAtlas2.glsl'>;
}
declare module 'echarts-gl/src/chart/graphGL/ForceAtlas2.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/ForceAtlas2'>;
}
declare module 'echarts-gl/src/chart/graphGL/ForceAtlas2GPU.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/ForceAtlas2GPU'>;
}
declare module 'echarts-gl/src/chart/graphGL/forceAtlas2Worker.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/forceAtlas2Worker'>;
}
declare module 'echarts-gl/src/chart/graphGL/GraphGLSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/GraphGLSeries'>;
}
declare module 'echarts-gl/src/chart/graphGL/GraphGLView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/graphGL/GraphGLView'>;
}
declare module 'echarts-gl/src/chart/line3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/line3D'>;
}
declare module 'echarts-gl/src/chart/line3D/Line3DSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/line3D/Line3DSeries'>;
}
declare module 'echarts-gl/src/chart/line3D/Line3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/line3D/Line3DView'>;
}
declare module 'echarts-gl/src/chart/lines3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D'>;
}
declare module 'echarts-gl/src/chart/lines3D/lines3DLayout.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/lines3DLayout'>;
}
declare module 'echarts-gl/src/chart/lines3D/Lines3DSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/Lines3DSeries'>;
}
declare module 'echarts-gl/src/chart/lines3D/Lines3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/Lines3DView'>;
}
declare module 'echarts-gl/src/chart/lines3D/shader/trail.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/shader/trail.glsl'>;
}
declare module 'echarts-gl/src/chart/lines3D/shader/trail2.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/shader/trail2.glsl'>;
}
declare module 'echarts-gl/src/chart/lines3D/TrailGeometry.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/TrailGeometry'>;
}
declare module 'echarts-gl/src/chart/lines3D/TrailMesh.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/TrailMesh'>;
}
declare module 'echarts-gl/src/chart/lines3D/TrailMesh2.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/lines3D/TrailMesh2'>;
}
declare module 'echarts-gl/src/chart/linesGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/linesGL'>;
}
declare module 'echarts-gl/src/chart/linesGL/LinesGLSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/linesGL/LinesGLSeries'>;
}
declare module 'echarts-gl/src/chart/linesGL/LinesGLView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/linesGL/LinesGLView'>;
}
declare module 'echarts-gl/src/chart/map3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/map3D'>;
}
declare module 'echarts-gl/src/chart/map3D/Map3DSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/map3D/Map3DSeries'>;
}
declare module 'echarts-gl/src/chart/map3D/Map3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/map3D/Map3DView'>;
}
declare module 'echarts-gl/src/chart/polygons3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/polygons3D'>;
}
declare module 'echarts-gl/src/chart/polygons3D/Polygons3DSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/polygons3D/Polygons3DSeries'>;
}
declare module 'echarts-gl/src/chart/polygons3D/Polygons3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/polygons3D/Polygons3DView'>;
}
declare module 'echarts-gl/src/chart/scatter3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/scatter3D'>;
}
declare module 'echarts-gl/src/chart/scatter3D/Scatter3DSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/scatter3D/Scatter3DSeries'>;
}
declare module 'echarts-gl/src/chart/scatter3D/Scatter3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/scatter3D/Scatter3DView'>;
}
declare module 'echarts-gl/src/chart/scatterGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/scatterGL'>;
}
declare module 'echarts-gl/src/chart/scatterGL/ScatterGLSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/scatterGL/ScatterGLSeries'>;
}
declare module 'echarts-gl/src/chart/scatterGL/ScatterGLView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/scatterGL/ScatterGLView'>;
}
declare module 'echarts-gl/src/chart/surface.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/surface'>;
}
declare module 'echarts-gl/src/chart/surface/surfaceLayout.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/surface/surfaceLayout'>;
}
declare module 'echarts-gl/src/chart/surface/SurfaceSeries.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/surface/SurfaceSeries'>;
}
declare module 'echarts-gl/src/chart/surface/SurfaceView.js' {
  declare module.exports: $Exports<'echarts-gl/src/chart/surface/SurfaceView'>;
}
declare module 'echarts-gl/src/component/common/componentLightMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/componentLightMixin'>;
}
declare module 'echarts-gl/src/component/common/componentPostEffectMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/componentPostEffectMixin'>;
}
declare module 'echarts-gl/src/component/common/componentShadingMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/componentShadingMixin'>;
}
declare module 'echarts-gl/src/component/common/componentViewControlMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/componentViewControlMixin'>;
}
declare module 'echarts-gl/src/component/common/Geo3DBuilder.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/Geo3DBuilder'>;
}
declare module 'echarts-gl/src/component/common/LabelsBuilder.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/LabelsBuilder'>;
}
declare module 'echarts-gl/src/component/common/SceneHelper.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/common/SceneHelper'>;
}
declare module 'echarts-gl/src/component/geo3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/geo3D'>;
}
declare module 'echarts-gl/src/component/geo3D/Geo3DModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/geo3D/Geo3DModel'>;
}
declare module 'echarts-gl/src/component/geo3D/Geo3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/geo3D/Geo3DView'>;
}
declare module 'echarts-gl/src/component/globe.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/globe'>;
}
declare module 'echarts-gl/src/component/globe/GlobeModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/globe/GlobeModel'>;
}
declare module 'echarts-gl/src/component/globe/GlobeView.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/globe/GlobeView'>;
}
declare module 'echarts-gl/src/component/grid3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D'>;
}
declare module 'echarts-gl/src/component/grid3D/axis3DDefault.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/axis3DDefault'>;
}
declare module 'echarts-gl/src/component/grid3D/Axis3DModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/Axis3DModel'>;
}
declare module 'echarts-gl/src/component/grid3D/createAxis3DModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/createAxis3DModel'>;
}
declare module 'echarts-gl/src/component/grid3D/Grid3DAxis.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/Grid3DAxis'>;
}
declare module 'echarts-gl/src/component/grid3D/Grid3DFace.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/Grid3DFace'>;
}
declare module 'echarts-gl/src/component/grid3D/Grid3DModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/Grid3DModel'>;
}
declare module 'echarts-gl/src/component/grid3D/Grid3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/grid3D/Grid3DView'>;
}
declare module 'echarts-gl/src/component/mapbox3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/mapbox3D'>;
}
declare module 'echarts-gl/src/component/mapbox3D/Mapbox3DLayer.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/mapbox3D/Mapbox3DLayer'>;
}
declare module 'echarts-gl/src/component/mapbox3D/Mapbox3DModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/mapbox3D/Mapbox3DModel'>;
}
declare module 'echarts-gl/src/component/mapbox3D/Mapbox3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/mapbox3D/Mapbox3DView'>;
}
declare module 'echarts-gl/src/component/maptalks3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/maptalks3D'>;
}
declare module 'echarts-gl/src/component/maptalks3D/Maptalks3DLayer.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/maptalks3D/Maptalks3DLayer'>;
}
declare module 'echarts-gl/src/component/maptalks3D/Maptalks3DModel.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/maptalks3D/Maptalks3DModel'>;
}
declare module 'echarts-gl/src/component/maptalks3D/Maptalks3DView.js' {
  declare module.exports: $Exports<'echarts-gl/src/component/maptalks3D/Maptalks3DView'>;
}
declare module 'echarts-gl/src/coord/geo3D/Geo3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/geo3D/Geo3D'>;
}
declare module 'echarts-gl/src/coord/geo3D/geo3DModelMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/geo3D/geo3DModelMixin'>;
}
declare module 'echarts-gl/src/coord/geo3DCreator.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/geo3DCreator'>;
}
declare module 'echarts-gl/src/coord/globe/Globe.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/globe/Globe'>;
}
declare module 'echarts-gl/src/coord/globeCreator.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/globeCreator'>;
}
declare module 'echarts-gl/src/coord/grid3D/Axis3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/grid3D/Axis3D'>;
}
declare module 'echarts-gl/src/coord/grid3D/Cartesian3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/grid3D/Cartesian3D'>;
}
declare module 'echarts-gl/src/coord/grid3DCreator.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/grid3DCreator'>;
}
declare module 'echarts-gl/src/coord/mapbox3D/Mapbox3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/mapbox3D/Mapbox3D'>;
}
declare module 'echarts-gl/src/coord/mapbox3DCreator.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/mapbox3DCreator'>;
}
declare module 'echarts-gl/src/coord/mapServiceCommon/createMapService3DCreator.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/mapServiceCommon/createMapService3DCreator'>;
}
declare module 'echarts-gl/src/coord/mapServiceCommon/MapService3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/mapServiceCommon/MapService3D'>;
}
declare module 'echarts-gl/src/coord/maptalks3D/Maptalks3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/maptalks3D/Maptalks3D'>;
}
declare module 'echarts-gl/src/coord/maptalks3DCreator.js' {
  declare module.exports: $Exports<'echarts-gl/src/coord/maptalks3DCreator'>;
}
declare module 'echarts-gl/src/core/LayerGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/core/LayerGL'>;
}
declare module 'echarts-gl/src/core/ViewGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/core/ViewGL'>;
}
declare module 'echarts-gl/src/echarts-gl.js' {
  declare module.exports: $Exports<'echarts-gl/src/echarts-gl'>;
}
declare module 'echarts-gl/src/effect/composite.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/composite'>;
}
declare module 'echarts-gl/src/effect/compositeMobile.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/compositeMobile'>;
}
declare module 'echarts-gl/src/effect/DOF.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/DOF.glsl'>;
}
declare module 'echarts-gl/src/effect/edge.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/edge.glsl'>;
}
declare module 'echarts-gl/src/effect/EdgePass.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/EdgePass'>;
}
declare module 'echarts-gl/src/effect/EffectCompositor.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/EffectCompositor'>;
}
declare module 'echarts-gl/src/effect/halton.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/halton'>;
}
declare module 'echarts-gl/src/effect/NormalPass.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/NormalPass'>;
}
declare module 'echarts-gl/src/effect/poissonKernel.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/poissonKernel'>;
}
declare module 'echarts-gl/src/effect/SSAO.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/SSAO.glsl'>;
}
declare module 'echarts-gl/src/effect/SSAOPass.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/SSAOPass'>;
}
declare module 'echarts-gl/src/effect/SSR.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/SSR.glsl'>;
}
declare module 'echarts-gl/src/effect/SSRPass.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/SSRPass'>;
}
declare module 'echarts-gl/src/effect/TemporalSuperSampling.js' {
  declare module.exports: $Exports<'echarts-gl/src/effect/TemporalSuperSampling'>;
}
declare module 'echarts-gl/src/preprocessor/backwardCompat.js' {
  declare module.exports: $Exports<'echarts-gl/src/preprocessor/backwardCompat'>;
}
declare module 'echarts-gl/src/util/animatableMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/animatableMixin'>;
}
declare module 'echarts-gl/src/util/earcut.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/earcut'>;
}
declare module 'echarts-gl/src/util/EChartsSurface.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/EChartsSurface'>;
}
declare module 'echarts-gl/src/util/format.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/format'>;
}
declare module 'echarts-gl/src/util/geometry/Bars3DGeometry.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/Bars3DGeometry'>;
}
declare module 'echarts-gl/src/util/geometry/dynamicConvertMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/dynamicConvertMixin'>;
}
declare module 'echarts-gl/src/util/geometry/Lines2D.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/Lines2D'>;
}
declare module 'echarts-gl/src/util/geometry/Lines3D.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/Lines3D'>;
}
declare module 'echarts-gl/src/util/geometry/Quads.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/Quads'>;
}
declare module 'echarts-gl/src/util/geometry/Sprites.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/Sprites'>;
}
declare module 'echarts-gl/src/util/geometry/trianglesSortMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/trianglesSortMixin'>;
}
declare module 'echarts-gl/src/util/geometry/verticesSortMixin.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/geometry/verticesSortMixin'>;
}
declare module 'echarts-gl/src/util/graphicGL.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/graphicGL'>;
}
declare module 'echarts-gl/src/util/mesh/LabelsMesh.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/mesh/LabelsMesh'>;
}
declare module 'echarts-gl/src/util/OrbitControl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/OrbitControl'>;
}
declare module 'echarts-gl/src/util/ProgressiveQuickSort.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/ProgressiveQuickSort'>;
}
declare module 'echarts-gl/src/util/retrieve.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/retrieve'>;
}
declare module 'echarts-gl/src/util/Roam2DControl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/Roam2DControl'>;
}
declare module 'echarts-gl/src/util/shader/color.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/color.glsl'>;
}
declare module 'echarts-gl/src/util/shader/common.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/common.glsl'>;
}
declare module 'echarts-gl/src/util/shader/displayShadow.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/displayShadow.glsl'>;
}
declare module 'echarts-gl/src/util/shader/hatching.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/hatching.glsl'>;
}
declare module 'echarts-gl/src/util/shader/labels.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/labels.glsl'>;
}
declare module 'echarts-gl/src/util/shader/lambert.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/lambert.glsl'>;
}
declare module 'echarts-gl/src/util/shader/lines2D.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/lines2D.glsl'>;
}
declare module 'echarts-gl/src/util/shader/lines3D.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/lines3D.glsl'>;
}
declare module 'echarts-gl/src/util/shader/motionBlur.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/motionBlur.glsl'>;
}
declare module 'echarts-gl/src/util/shader/normal.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/normal.glsl'>;
}
declare module 'echarts-gl/src/util/shader/realistic.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/realistic.glsl'>;
}
declare module 'echarts-gl/src/util/shader/shadow.glsl.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/shader/shadow.glsl'>;
}
declare module 'echarts-gl/src/util/sprite.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/sprite'>;
}
declare module 'echarts-gl/src/util/sunCalc.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/sunCalc'>;
}
declare module 'echarts-gl/src/util/Triangulation.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/Triangulation'>;
}
declare module 'echarts-gl/src/util/ZRTextureAtlasSurface.js' {
  declare module.exports: $Exports<'echarts-gl/src/util/ZRTextureAtlasSurface'>;
}
declare module 'echarts-gl/webpack.config.js' {
  declare module.exports: $Exports<'echarts-gl/webpack.config'>;
}
