// flow-typed signature: 107b7d5fc03954757e4d80dafc981d76
// flow-typed version: <<STUB>>/hls.js_v^0.12.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hls.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hls.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hls.js/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'hls.js/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'hls.js/dist/hls-demo' {
  declare module.exports: any;
}

declare module 'hls.js/dist/hls' {
  declare module.exports: any;
}

declare module 'hls.js/dist/hls.light' {
  declare module.exports: any;
}

declare module 'hls.js/dist/hls.light.min' {
  declare module.exports: any;
}

declare module 'hls.js/dist/hls.min' {
  declare module.exports: any;
}

declare module 'hls.js/karma.conf' {
  declare module.exports: any;
}

declare module 'hls.js/scripts/check-already-published' {
  declare module.exports: any;
}

declare module 'hls.js/scripts/foldersize' {
  declare module.exports: any;
}

declare module 'hls.js/scripts/set-package-version' {
  declare module.exports: any;
}

declare module 'hls.js/src/config' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/abr-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/audio-stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/audio-track-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/base-stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/buffer-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/cap-level-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/eme-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/fps-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/fragment-finders' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/fragment-tracker' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/gap-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/id3-track-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/level-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/level-helper' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/subtitle-stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/subtitle-track-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/controller/timeline-controller' {
  declare module.exports: any;
}

declare module 'hls.js/src/crypt/aes-crypto' {
  declare module.exports: any;
}

declare module 'hls.js/src/crypt/aes-decryptor' {
  declare module.exports: any;
}

declare module 'hls.js/src/crypt/decrypter' {
  declare module.exports: any;
}

declare module 'hls.js/src/crypt/fast-aes-key' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/aacdemuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/adts' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/demuxer-inline' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/demuxer-worker' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/demuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/exp-golomb' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/id3' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/mp3demuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/mp4demuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/mpegaudio' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/sample-aes' {
  declare module.exports: any;
}

declare module 'hls.js/src/demux/tsdemuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/empty' {
  declare module.exports: any;
}

declare module 'hls.js/src/errors' {
  declare module.exports: any;
}

declare module 'hls.js/src/event-handler' {
  declare module.exports: any;
}

declare module 'hls.js/src/events' {
  declare module.exports: any;
}

declare module 'hls.js/src/hls' {
  declare module.exports: any;
}

declare module 'hls.js/src/is-supported' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/fragment-loader' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/fragment' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/key-loader' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/level-key' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/level' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/m3u8-parser' {
  declare module.exports: any;
}

declare module 'hls.js/src/loader/playlist-loader' {
  declare module.exports: any;
}

declare module 'hls.js/src/observer' {
  declare module.exports: any;
}

declare module 'hls.js/src/polyfills/number' {
  declare module.exports: any;
}

declare module 'hls.js/src/remux/aac-helper' {
  declare module.exports: any;
}

declare module 'hls.js/src/remux/dummy-remuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/remux/mp4-generator' {
  declare module.exports: any;
}

declare module 'hls.js/src/remux/mp4-remuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/remux/passthrough-remuxer' {
  declare module.exports: any;
}

declare module 'hls.js/src/task-loop' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/attr-list' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/binary-search' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/buffer-helper' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/cea-608-parser' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/codecs' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/cues' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/discontinuities' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/ewma-bandwidth-estimator' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/ewma' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/fetch-loader' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/get-self-scope' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/hex' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/logger' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/mediakeys-helper' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/mediasource-helper' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/output-filter' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/texttrack-utils' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/time-ranges' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/vttcue' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/vttparser' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/webvtt-parser' {
  declare module.exports: any;
}

declare module 'hls.js/src/utils/xhr-loader' {
  declare module.exports: any;
}

declare module 'hls.js/tests/functional/auto/setup' {
  declare module.exports: any;
}

declare module 'hls.js/tests/functional/auto/testbench' {
  declare module.exports: any;
}

declare module 'hls.js/tests/mocks/data' {
  declare module.exports: any;
}

declare module 'hls.js/tests/mocks/hls.mock' {
  declare module.exports: any;
}

declare module 'hls.js/tests/test-streams' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/abr-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/audio-track-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/base-stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/buffer-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/cap-level-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/eme-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/ewma-bandwidth-estimator' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/fragment-finders' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/fragment-tracker' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/gap-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/level-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/level-helper' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/subtitle-stream-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/subtitle-track-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/controller/timeline-controller' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/crypt/aes-decryptor' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/demuxer/demuxer' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/dummy' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/events' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/loader/fragment' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/loader/level' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/loader/playlist-loader' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/utils/attr-list' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/utils/binary-search' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/utils/buffer-helper' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/utils/discontinuities' {
  declare module.exports: any;
}

declare module 'hls.js/tests/unit/utils/output-filter' {
  declare module.exports: any;
}

declare module 'hls.js/tools/mp4-inspect' {
  declare module.exports: any;
}

declare module 'hls.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hls.js/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'hls.js/coverage/lcov-report/prettify'>;
}
declare module 'hls.js/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'hls.js/coverage/lcov-report/sorter'>;
}
declare module 'hls.js/dist/hls-demo.js' {
  declare module.exports: $Exports<'hls.js/dist/hls-demo'>;
}
declare module 'hls.js/dist/hls.js' {
  declare module.exports: $Exports<'hls.js/dist/hls'>;
}
declare module 'hls.js/dist/hls.light.js' {
  declare module.exports: $Exports<'hls.js/dist/hls.light'>;
}
declare module 'hls.js/dist/hls.light.min.js' {
  declare module.exports: $Exports<'hls.js/dist/hls.light.min'>;
}
declare module 'hls.js/dist/hls.min.js' {
  declare module.exports: $Exports<'hls.js/dist/hls.min'>;
}
declare module 'hls.js/karma.conf.js' {
  declare module.exports: $Exports<'hls.js/karma.conf'>;
}
declare module 'hls.js/scripts/check-already-published.js' {
  declare module.exports: $Exports<'hls.js/scripts/check-already-published'>;
}
declare module 'hls.js/scripts/foldersize.js' {
  declare module.exports: $Exports<'hls.js/scripts/foldersize'>;
}
declare module 'hls.js/scripts/set-package-version.js' {
  declare module.exports: $Exports<'hls.js/scripts/set-package-version'>;
}
declare module 'hls.js/src/config.js' {
  declare module.exports: $Exports<'hls.js/src/config'>;
}
declare module 'hls.js/src/controller/abr-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/abr-controller'>;
}
declare module 'hls.js/src/controller/audio-stream-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/audio-stream-controller'>;
}
declare module 'hls.js/src/controller/audio-track-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/audio-track-controller'>;
}
declare module 'hls.js/src/controller/base-stream-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/base-stream-controller'>;
}
declare module 'hls.js/src/controller/buffer-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/buffer-controller'>;
}
declare module 'hls.js/src/controller/cap-level-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/cap-level-controller'>;
}
declare module 'hls.js/src/controller/eme-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/eme-controller'>;
}
declare module 'hls.js/src/controller/fps-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/fps-controller'>;
}
declare module 'hls.js/src/controller/fragment-finders.js' {
  declare module.exports: $Exports<'hls.js/src/controller/fragment-finders'>;
}
declare module 'hls.js/src/controller/fragment-tracker.js' {
  declare module.exports: $Exports<'hls.js/src/controller/fragment-tracker'>;
}
declare module 'hls.js/src/controller/gap-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/gap-controller'>;
}
declare module 'hls.js/src/controller/id3-track-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/id3-track-controller'>;
}
declare module 'hls.js/src/controller/level-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/level-controller'>;
}
declare module 'hls.js/src/controller/level-helper.js' {
  declare module.exports: $Exports<'hls.js/src/controller/level-helper'>;
}
declare module 'hls.js/src/controller/stream-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/stream-controller'>;
}
declare module 'hls.js/src/controller/subtitle-stream-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/subtitle-stream-controller'>;
}
declare module 'hls.js/src/controller/subtitle-track-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/subtitle-track-controller'>;
}
declare module 'hls.js/src/controller/timeline-controller.js' {
  declare module.exports: $Exports<'hls.js/src/controller/timeline-controller'>;
}
declare module 'hls.js/src/crypt/aes-crypto.js' {
  declare module.exports: $Exports<'hls.js/src/crypt/aes-crypto'>;
}
declare module 'hls.js/src/crypt/aes-decryptor.js' {
  declare module.exports: $Exports<'hls.js/src/crypt/aes-decryptor'>;
}
declare module 'hls.js/src/crypt/decrypter.js' {
  declare module.exports: $Exports<'hls.js/src/crypt/decrypter'>;
}
declare module 'hls.js/src/crypt/fast-aes-key.js' {
  declare module.exports: $Exports<'hls.js/src/crypt/fast-aes-key'>;
}
declare module 'hls.js/src/demux/aacdemuxer.js' {
  declare module.exports: $Exports<'hls.js/src/demux/aacdemuxer'>;
}
declare module 'hls.js/src/demux/adts.js' {
  declare module.exports: $Exports<'hls.js/src/demux/adts'>;
}
declare module 'hls.js/src/demux/demuxer-inline.js' {
  declare module.exports: $Exports<'hls.js/src/demux/demuxer-inline'>;
}
declare module 'hls.js/src/demux/demuxer-worker.js' {
  declare module.exports: $Exports<'hls.js/src/demux/demuxer-worker'>;
}
declare module 'hls.js/src/demux/demuxer.js' {
  declare module.exports: $Exports<'hls.js/src/demux/demuxer'>;
}
declare module 'hls.js/src/demux/exp-golomb.js' {
  declare module.exports: $Exports<'hls.js/src/demux/exp-golomb'>;
}
declare module 'hls.js/src/demux/id3.js' {
  declare module.exports: $Exports<'hls.js/src/demux/id3'>;
}
declare module 'hls.js/src/demux/mp3demuxer.js' {
  declare module.exports: $Exports<'hls.js/src/demux/mp3demuxer'>;
}
declare module 'hls.js/src/demux/mp4demuxer.js' {
  declare module.exports: $Exports<'hls.js/src/demux/mp4demuxer'>;
}
declare module 'hls.js/src/demux/mpegaudio.js' {
  declare module.exports: $Exports<'hls.js/src/demux/mpegaudio'>;
}
declare module 'hls.js/src/demux/sample-aes.js' {
  declare module.exports: $Exports<'hls.js/src/demux/sample-aes'>;
}
declare module 'hls.js/src/demux/tsdemuxer.js' {
  declare module.exports: $Exports<'hls.js/src/demux/tsdemuxer'>;
}
declare module 'hls.js/src/empty.js' {
  declare module.exports: $Exports<'hls.js/src/empty'>;
}
declare module 'hls.js/src/errors.js' {
  declare module.exports: $Exports<'hls.js/src/errors'>;
}
declare module 'hls.js/src/event-handler.js' {
  declare module.exports: $Exports<'hls.js/src/event-handler'>;
}
declare module 'hls.js/src/events.js' {
  declare module.exports: $Exports<'hls.js/src/events'>;
}
declare module 'hls.js/src/hls.js' {
  declare module.exports: $Exports<'hls.js/src/hls'>;
}
declare module 'hls.js/src/is-supported.js' {
  declare module.exports: $Exports<'hls.js/src/is-supported'>;
}
declare module 'hls.js/src/loader/fragment-loader.js' {
  declare module.exports: $Exports<'hls.js/src/loader/fragment-loader'>;
}
declare module 'hls.js/src/loader/fragment.js' {
  declare module.exports: $Exports<'hls.js/src/loader/fragment'>;
}
declare module 'hls.js/src/loader/key-loader.js' {
  declare module.exports: $Exports<'hls.js/src/loader/key-loader'>;
}
declare module 'hls.js/src/loader/level-key.js' {
  declare module.exports: $Exports<'hls.js/src/loader/level-key'>;
}
declare module 'hls.js/src/loader/level.js' {
  declare module.exports: $Exports<'hls.js/src/loader/level'>;
}
declare module 'hls.js/src/loader/m3u8-parser.js' {
  declare module.exports: $Exports<'hls.js/src/loader/m3u8-parser'>;
}
declare module 'hls.js/src/loader/playlist-loader.js' {
  declare module.exports: $Exports<'hls.js/src/loader/playlist-loader'>;
}
declare module 'hls.js/src/observer.js' {
  declare module.exports: $Exports<'hls.js/src/observer'>;
}
declare module 'hls.js/src/polyfills/number.js' {
  declare module.exports: $Exports<'hls.js/src/polyfills/number'>;
}
declare module 'hls.js/src/remux/aac-helper.js' {
  declare module.exports: $Exports<'hls.js/src/remux/aac-helper'>;
}
declare module 'hls.js/src/remux/dummy-remuxer.js' {
  declare module.exports: $Exports<'hls.js/src/remux/dummy-remuxer'>;
}
declare module 'hls.js/src/remux/mp4-generator.js' {
  declare module.exports: $Exports<'hls.js/src/remux/mp4-generator'>;
}
declare module 'hls.js/src/remux/mp4-remuxer.js' {
  declare module.exports: $Exports<'hls.js/src/remux/mp4-remuxer'>;
}
declare module 'hls.js/src/remux/passthrough-remuxer.js' {
  declare module.exports: $Exports<'hls.js/src/remux/passthrough-remuxer'>;
}
declare module 'hls.js/src/task-loop.js' {
  declare module.exports: $Exports<'hls.js/src/task-loop'>;
}
declare module 'hls.js/src/utils/attr-list.js' {
  declare module.exports: $Exports<'hls.js/src/utils/attr-list'>;
}
declare module 'hls.js/src/utils/binary-search.js' {
  declare module.exports: $Exports<'hls.js/src/utils/binary-search'>;
}
declare module 'hls.js/src/utils/buffer-helper.js' {
  declare module.exports: $Exports<'hls.js/src/utils/buffer-helper'>;
}
declare module 'hls.js/src/utils/cea-608-parser.js' {
  declare module.exports: $Exports<'hls.js/src/utils/cea-608-parser'>;
}
declare module 'hls.js/src/utils/codecs.js' {
  declare module.exports: $Exports<'hls.js/src/utils/codecs'>;
}
declare module 'hls.js/src/utils/cues.js' {
  declare module.exports: $Exports<'hls.js/src/utils/cues'>;
}
declare module 'hls.js/src/utils/discontinuities.js' {
  declare module.exports: $Exports<'hls.js/src/utils/discontinuities'>;
}
declare module 'hls.js/src/utils/ewma-bandwidth-estimator.js' {
  declare module.exports: $Exports<'hls.js/src/utils/ewma-bandwidth-estimator'>;
}
declare module 'hls.js/src/utils/ewma.js' {
  declare module.exports: $Exports<'hls.js/src/utils/ewma'>;
}
declare module 'hls.js/src/utils/fetch-loader.js' {
  declare module.exports: $Exports<'hls.js/src/utils/fetch-loader'>;
}
declare module 'hls.js/src/utils/get-self-scope.js' {
  declare module.exports: $Exports<'hls.js/src/utils/get-self-scope'>;
}
declare module 'hls.js/src/utils/hex.js' {
  declare module.exports: $Exports<'hls.js/src/utils/hex'>;
}
declare module 'hls.js/src/utils/logger.js' {
  declare module.exports: $Exports<'hls.js/src/utils/logger'>;
}
declare module 'hls.js/src/utils/mediakeys-helper.js' {
  declare module.exports: $Exports<'hls.js/src/utils/mediakeys-helper'>;
}
declare module 'hls.js/src/utils/mediasource-helper.js' {
  declare module.exports: $Exports<'hls.js/src/utils/mediasource-helper'>;
}
declare module 'hls.js/src/utils/output-filter.js' {
  declare module.exports: $Exports<'hls.js/src/utils/output-filter'>;
}
declare module 'hls.js/src/utils/texttrack-utils.js' {
  declare module.exports: $Exports<'hls.js/src/utils/texttrack-utils'>;
}
declare module 'hls.js/src/utils/time-ranges.js' {
  declare module.exports: $Exports<'hls.js/src/utils/time-ranges'>;
}
declare module 'hls.js/src/utils/vttcue.js' {
  declare module.exports: $Exports<'hls.js/src/utils/vttcue'>;
}
declare module 'hls.js/src/utils/vttparser.js' {
  declare module.exports: $Exports<'hls.js/src/utils/vttparser'>;
}
declare module 'hls.js/src/utils/webvtt-parser.js' {
  declare module.exports: $Exports<'hls.js/src/utils/webvtt-parser'>;
}
declare module 'hls.js/src/utils/xhr-loader.js' {
  declare module.exports: $Exports<'hls.js/src/utils/xhr-loader'>;
}
declare module 'hls.js/tests/functional/auto/setup.js' {
  declare module.exports: $Exports<'hls.js/tests/functional/auto/setup'>;
}
declare module 'hls.js/tests/functional/auto/testbench.js' {
  declare module.exports: $Exports<'hls.js/tests/functional/auto/testbench'>;
}
declare module 'hls.js/tests/mocks/data.js' {
  declare module.exports: $Exports<'hls.js/tests/mocks/data'>;
}
declare module 'hls.js/tests/mocks/hls.mock.js' {
  declare module.exports: $Exports<'hls.js/tests/mocks/hls.mock'>;
}
declare module 'hls.js/tests/test-streams.js' {
  declare module.exports: $Exports<'hls.js/tests/test-streams'>;
}
declare module 'hls.js/tests/unit/controller/abr-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/abr-controller'>;
}
declare module 'hls.js/tests/unit/controller/audio-track-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/audio-track-controller'>;
}
declare module 'hls.js/tests/unit/controller/base-stream-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/base-stream-controller'>;
}
declare module 'hls.js/tests/unit/controller/buffer-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/buffer-controller'>;
}
declare module 'hls.js/tests/unit/controller/cap-level-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/cap-level-controller'>;
}
declare module 'hls.js/tests/unit/controller/eme-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/eme-controller'>;
}
declare module 'hls.js/tests/unit/controller/ewma-bandwidth-estimator.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/ewma-bandwidth-estimator'>;
}
declare module 'hls.js/tests/unit/controller/fragment-finders.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/fragment-finders'>;
}
declare module 'hls.js/tests/unit/controller/fragment-tracker.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/fragment-tracker'>;
}
declare module 'hls.js/tests/unit/controller/gap-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/gap-controller'>;
}
declare module 'hls.js/tests/unit/controller/level-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/level-controller'>;
}
declare module 'hls.js/tests/unit/controller/level-helper.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/level-helper'>;
}
declare module 'hls.js/tests/unit/controller/stream-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/stream-controller'>;
}
declare module 'hls.js/tests/unit/controller/subtitle-stream-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/subtitle-stream-controller'>;
}
declare module 'hls.js/tests/unit/controller/subtitle-track-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/subtitle-track-controller'>;
}
declare module 'hls.js/tests/unit/controller/timeline-controller.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/controller/timeline-controller'>;
}
declare module 'hls.js/tests/unit/crypt/aes-decryptor.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/crypt/aes-decryptor'>;
}
declare module 'hls.js/tests/unit/demuxer/demuxer.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/demuxer/demuxer'>;
}
declare module 'hls.js/tests/unit/dummy.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/dummy'>;
}
declare module 'hls.js/tests/unit/events.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/events'>;
}
declare module 'hls.js/tests/unit/loader/fragment.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/loader/fragment'>;
}
declare module 'hls.js/tests/unit/loader/level.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/loader/level'>;
}
declare module 'hls.js/tests/unit/loader/playlist-loader.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/loader/playlist-loader'>;
}
declare module 'hls.js/tests/unit/utils/attr-list.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/utils/attr-list'>;
}
declare module 'hls.js/tests/unit/utils/binary-search.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/utils/binary-search'>;
}
declare module 'hls.js/tests/unit/utils/buffer-helper.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/utils/buffer-helper'>;
}
declare module 'hls.js/tests/unit/utils/discontinuities.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/utils/discontinuities'>;
}
declare module 'hls.js/tests/unit/utils/output-filter.js' {
  declare module.exports: $Exports<'hls.js/tests/unit/utils/output-filter'>;
}
declare module 'hls.js/tools/mp4-inspect.js' {
  declare module.exports: $Exports<'hls.js/tools/mp4-inspect'>;
}
declare module 'hls.js/webpack.config.js' {
  declare module.exports: $Exports<'hls.js/webpack.config'>;
}
