// flow-typed signature: c2e7bd8b717062fd727145eb25faf504
// flow-typed version: <<STUB>>/ip-address_v^5.8.9/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ip-address'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ip-address' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ip-address/dist/ip-address-globals' {
  declare module.exports: any;
}

declare module 'ip-address/ip-address-globals' {
  declare module.exports: any;
}

declare module 'ip-address/ip-address' {
  declare module.exports: any;
}

declare module 'ip-address/lib/common' {
  declare module.exports: any;
}

declare module 'ip-address/lib/ipv4' {
  declare module.exports: any;
}

declare module 'ip-address/lib/ipv6' {
  declare module.exports: any;
}

declare module 'ip-address/lib/v4/constants' {
  declare module.exports: any;
}

declare module 'ip-address/lib/v6/attributes' {
  declare module.exports: any;
}

declare module 'ip-address/lib/v6/constants' {
  declare module.exports: any;
}

declare module 'ip-address/lib/v6/helpers' {
  declare module.exports: any;
}

declare module 'ip-address/lib/v6/html' {
  declare module.exports: any;
}

declare module 'ip-address/lib/v6/regular-expressions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ip-address/dist/ip-address-globals.js' {
  declare module.exports: $Exports<'ip-address/dist/ip-address-globals'>;
}
declare module 'ip-address/ip-address-globals.js' {
  declare module.exports: $Exports<'ip-address/ip-address-globals'>;
}
declare module 'ip-address/ip-address.js' {
  declare module.exports: $Exports<'ip-address/ip-address'>;
}
declare module 'ip-address/lib/common.js' {
  declare module.exports: $Exports<'ip-address/lib/common'>;
}
declare module 'ip-address/lib/ipv4.js' {
  declare module.exports: $Exports<'ip-address/lib/ipv4'>;
}
declare module 'ip-address/lib/ipv6.js' {
  declare module.exports: $Exports<'ip-address/lib/ipv6'>;
}
declare module 'ip-address/lib/v4/constants.js' {
  declare module.exports: $Exports<'ip-address/lib/v4/constants'>;
}
declare module 'ip-address/lib/v6/attributes.js' {
  declare module.exports: $Exports<'ip-address/lib/v6/attributes'>;
}
declare module 'ip-address/lib/v6/constants.js' {
  declare module.exports: $Exports<'ip-address/lib/v6/constants'>;
}
declare module 'ip-address/lib/v6/helpers.js' {
  declare module.exports: $Exports<'ip-address/lib/v6/helpers'>;
}
declare module 'ip-address/lib/v6/html.js' {
  declare module.exports: $Exports<'ip-address/lib/v6/html'>;
}
declare module 'ip-address/lib/v6/regular-expressions.js' {
  declare module.exports: $Exports<'ip-address/lib/v6/regular-expressions'>;
}
