// flow-typed signature: 6e80bd259523b5b9b5e247c938e0d434
// flow-typed version: <<STUB>>/libp2p-pnet_v^0.1.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libp2p-pnet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libp2p-pnet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libp2p-pnet/src/crypto' {
  declare module.exports: any;
}

declare module 'libp2p-pnet/src/errors' {
  declare module.exports: any;
}

declare module 'libp2p-pnet/src/index' {
  declare module.exports: any;
}

declare module 'libp2p-pnet/src/key-generator' {
  declare module.exports: any;
}

declare module 'libp2p-pnet/src/state' {
  declare module.exports: any;
}

declare module 'libp2p-pnet/test/pnet.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libp2p-pnet/src/crypto.js' {
  declare module.exports: $Exports<'libp2p-pnet/src/crypto'>;
}
declare module 'libp2p-pnet/src/errors.js' {
  declare module.exports: $Exports<'libp2p-pnet/src/errors'>;
}
declare module 'libp2p-pnet/src/index.js' {
  declare module.exports: $Exports<'libp2p-pnet/src/index'>;
}
declare module 'libp2p-pnet/src/key-generator.js' {
  declare module.exports: $Exports<'libp2p-pnet/src/key-generator'>;
}
declare module 'libp2p-pnet/src/state.js' {
  declare module.exports: $Exports<'libp2p-pnet/src/state'>;
}
declare module 'libp2p-pnet/test/pnet.spec.js' {
  declare module.exports: $Exports<'libp2p-pnet/test/pnet.spec'>;
}
