// flow-typed signature: d9ed878adfaf24064ae4e3f5dd1dd6de
// flow-typed version: <<STUB>>/multibase_v^0.6.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multibase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multibase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multibase/dist/index' {
  declare module.exports: any;
}

declare module 'multibase/dist/index.min' {
  declare module.exports: any;
}

declare module 'multibase/example' {
  declare module.exports: any;
}

declare module 'multibase/src/base' {
  declare module.exports: any;
}

declare module 'multibase/src/base16' {
  declare module.exports: any;
}

declare module 'multibase/src/base32' {
  declare module.exports: any;
}

declare module 'multibase/src/base64' {
  declare module.exports: any;
}

declare module 'multibase/src/constants' {
  declare module.exports: any;
}

declare module 'multibase/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multibase/dist/index.js' {
  declare module.exports: $Exports<'multibase/dist/index'>;
}
declare module 'multibase/dist/index.min.js' {
  declare module.exports: $Exports<'multibase/dist/index.min'>;
}
declare module 'multibase/example.js' {
  declare module.exports: $Exports<'multibase/example'>;
}
declare module 'multibase/src/base.js' {
  declare module.exports: $Exports<'multibase/src/base'>;
}
declare module 'multibase/src/base16.js' {
  declare module.exports: $Exports<'multibase/src/base16'>;
}
declare module 'multibase/src/base32.js' {
  declare module.exports: $Exports<'multibase/src/base32'>;
}
declare module 'multibase/src/base64.js' {
  declare module.exports: $Exports<'multibase/src/base64'>;
}
declare module 'multibase/src/constants.js' {
  declare module.exports: $Exports<'multibase/src/constants'>;
}
declare module 'multibase/src/index.js' {
  declare module.exports: $Exports<'multibase/src/index'>;
}
