// flow-typed signature: d8c24e0fbed68c10e74579cf199a6fa5
// flow-typed version: <<STUB>>/ngrok_v3.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ngrok'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ngrok' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ngrok/postinstall' {
  declare module.exports: any;
}

declare module 'ngrok/process' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ngrok/index' {
  declare module.exports: $Exports<'ngrok'>;
}
declare module 'ngrok/index.js' {
  declare module.exports: $Exports<'ngrok'>;
}
declare module 'ngrok/postinstall.js' {
  declare module.exports: $Exports<'ngrok/postinstall'>;
}
declare module 'ngrok/process.js' {
  declare module.exports: $Exports<'ngrok/process'>;
}
