// flow-typed signature: 9de85e31a5dd13c2d8d946106d737ea0
// flow-typed version: <<STUB>>/random-ip_v^0.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-ip/test/index' {
  declare module.exports: any;
}

declare module 'random-ip/test/ipv4' {
  declare module.exports: any;
}

declare module 'random-ip/test/ipv6' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-ip/index' {
  declare module.exports: $Exports<'random-ip'>;
}
declare module 'random-ip/index.js' {
  declare module.exports: $Exports<'random-ip'>;
}
declare module 'random-ip/test/index.js' {
  declare module.exports: $Exports<'random-ip/test/index'>;
}
declare module 'random-ip/test/ipv4.js' {
  declare module.exports: $Exports<'random-ip/test/ipv4'>;
}
declare module 'random-ip/test/ipv6.js' {
  declare module.exports: $Exports<'random-ip/test/ipv6'>;
}
