// flow-typed signature: ba575ed060296f1c6b62ed59c4eca443
// flow-typed version: <<STUB>>/redux-saga_v1.0.0-rc.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga/dist/chunk-0077808e' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/chunk-0e1a6d35' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/chunk-b503a2ff' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.dev.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.esm' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-core.prod.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.dev.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.esm' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga-effects.prod.cjs' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.min.umd' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga/dist/chunk-0077808e.js' {
  declare module.exports: $Exports<'redux-saga/dist/chunk-0077808e'>;
}
declare module 'redux-saga/dist/chunk-0e1a6d35.js' {
  declare module.exports: $Exports<'redux-saga/dist/chunk-0e1a6d35'>;
}
declare module 'redux-saga/dist/chunk-b503a2ff.js' {
  declare module.exports: $Exports<'redux-saga/dist/chunk-b503a2ff'>;
}
declare module 'redux-saga/dist/redux-saga-core.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-core.dev.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.dev.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-core.esm.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.esm'>;
}
declare module 'redux-saga/dist/redux-saga-core.prod.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-core.prod.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-effects.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-effects.dev.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.dev.cjs'>;
}
declare module 'redux-saga/dist/redux-saga-effects.esm.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.esm'>;
}
declare module 'redux-saga/dist/redux-saga-effects.prod.cjs.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga-effects.prod.cjs'>;
}
declare module 'redux-saga/dist/redux-saga.min.umd.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.min.umd'>;
}
declare module 'redux-saga/dist/redux-saga.umd.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.umd'>;
}
