// flow-typed signature: 1793051e73bfdc7fb61d63c9eda77423
// flow-typed version: <<STUB>>/safe-buffer_v^5.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safe-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safe-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'safe-buffer/index' {
  declare module.exports: $Exports<'safe-buffer'>;
}
declare module 'safe-buffer/index.js' {
  declare module.exports: $Exports<'safe-buffer'>;
}
