// flow-typed signature: 351feb439bc24145c977696b88852664
// flow-typed version: <<STUB>>/user-agent-parser_v^0.6.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'user-agent-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'user-agent-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'user-agent-parser/src/ua-parser' {
  declare module.exports: any;
}

declare module 'user-agent-parser/src/ua-parser.min' {
  declare module.exports: any;
}

declare module 'user-agent-parser/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'user-agent-parser/src/ua-parser.js' {
  declare module.exports: $Exports<'user-agent-parser/src/ua-parser'>;
}
declare module 'user-agent-parser/src/ua-parser.min.js' {
  declare module.exports: $Exports<'user-agent-parser/src/ua-parser.min'>;
}
declare module 'user-agent-parser/test/test.js' {
  declare module.exports: $Exports<'user-agent-parser/test/test'>;
}
