// flow-typed signature: cdc5824953a0a985ccbd77e389e3de51
// flow-typed version: <<STUB>>/workerize-loader_v^1.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workerize-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workerize-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workerize-loader/dist/index' {
  declare module.exports: any;
}

declare module 'workerize-loader/dist/rpc-worker-loader' {
  declare module.exports: any;
}

declare module 'workerize-loader/dist/rpc-wrapper' {
  declare module.exports: any;
}

declare module 'workerize-loader/src/index' {
  declare module.exports: any;
}

declare module 'workerize-loader/src/rpc-worker-loader' {
  declare module.exports: any;
}

declare module 'workerize-loader/src/rpc-wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workerize-loader/dist/index.js' {
  declare module.exports: $Exports<'workerize-loader/dist/index'>;
}
declare module 'workerize-loader/dist/rpc-worker-loader.js' {
  declare module.exports: $Exports<'workerize-loader/dist/rpc-worker-loader'>;
}
declare module 'workerize-loader/dist/rpc-wrapper.js' {
  declare module.exports: $Exports<'workerize-loader/dist/rpc-wrapper'>;
}
declare module 'workerize-loader/src/index.js' {
  declare module.exports: $Exports<'workerize-loader/src/index'>;
}
declare module 'workerize-loader/src/rpc-worker-loader.js' {
  declare module.exports: $Exports<'workerize-loader/src/rpc-worker-loader'>;
}
declare module 'workerize-loader/src/rpc-wrapper.js' {
  declare module.exports: $Exports<'workerize-loader/src/rpc-wrapper'>;
}
