// flow-typed signature: 1708976c6c2c95f7a65b2b1cfb2f6df1
// flow-typed version: <<STUB>>/@bunchtogether/webrtc-messagepack_v^1.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bunchtogether/webrtc-messagepack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bunchtogether/webrtc-messagepack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bunchtogether/webrtc-messagepack/dist/index' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-messagepack/dist/types' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-messagepack/flow/jest' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-messagepack/flow/uWebSockets' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-messagepack/src/index' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-messagepack/src/types' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-messagepack/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bunchtogether/webrtc-messagepack/dist/index.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/dist/index'>;
}
declare module '@bunchtogether/webrtc-messagepack/dist/types.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/dist/types'>;
}
declare module '@bunchtogether/webrtc-messagepack/flow/jest.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/flow/jest'>;
}
declare module '@bunchtogether/webrtc-messagepack/flow/uWebSockets.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/flow/uWebSockets'>;
}
declare module '@bunchtogether/webrtc-messagepack/src/index.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/src/index'>;
}
declare module '@bunchtogether/webrtc-messagepack/src/types.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/src/types'>;
}
declare module '@bunchtogether/webrtc-messagepack/test/index.test.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-messagepack/test/index.test'>;
}
