// flow-typed signature: ba8a9af687c1817e590acfc8c8d46a20
// flow-typed version: <<STUB>>/@bunchtogether/webrtc-client_v^1.0.10/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bunchtogether/webrtc-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bunchtogether/webrtc-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bunchtogether/webrtc-client/dist/devices' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/dist/index' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/dist/logger' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/flow/jest' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/flow/uWebSockets' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/src/devices' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/src/index' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/src/logger' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/devices.test' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/index.test' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/EnhancedEventEmitter' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/FakeHandler' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/fakeParameters' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/h264-profile-level-id' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/Logger' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/ortc' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/device/utils' {
  declare module.exports: any;
}

declare module '@bunchtogether/webrtc-client/test/lib/router-capabilities' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bunchtogether/webrtc-client/dist/devices.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/dist/devices'>;
}
declare module '@bunchtogether/webrtc-client/dist/index.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/dist/index'>;
}
declare module '@bunchtogether/webrtc-client/dist/logger.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/dist/logger'>;
}
declare module '@bunchtogether/webrtc-client/flow/jest.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/flow/jest'>;
}
declare module '@bunchtogether/webrtc-client/flow/uWebSockets.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/flow/uWebSockets'>;
}
declare module '@bunchtogether/webrtc-client/src/devices.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/src/devices'>;
}
declare module '@bunchtogether/webrtc-client/src/index.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/src/index'>;
}
declare module '@bunchtogether/webrtc-client/src/logger.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/src/logger'>;
}
declare module '@bunchtogether/webrtc-client/test/devices.test.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/devices.test'>;
}
declare module '@bunchtogether/webrtc-client/test/index.test.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/index.test'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/EnhancedEventEmitter.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/EnhancedEventEmitter'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/FakeHandler.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/FakeHandler'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/fakeParameters.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/fakeParameters'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/h264-profile-level-id.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/h264-profile-level-id'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/Logger.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/Logger'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/ortc.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/ortc'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/device/utils.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/device/utils'>;
}
declare module '@bunchtogether/webrtc-client/test/lib/router-capabilities.js' {
  declare module.exports: $Exports<'@bunchtogether/webrtc-client/test/lib/router-capabilities'>;
}
